name: MineFetch
version: 1.0
main: xyz.guyb.MineFetch
authors:
  - Guy Brown (Lineage_MC)
commands:
  fetch:
    permission: MineFetch.fetch
    usage: /fetch
    aliases:
      - MineFetch
      - SysInfo






